---
resources:
# The repo with our Dockerfile
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/hugosamuel/stranger.git
    branch: main

# Where we will push the image
- name: simple-image
  type: registry-image
  icon: docker
  source:
    # You need to provide these variables when
    # setting the pipeline
    repository:  slw.jfrog.io/((repo-img-name))/strapi
    tag: "((?<version>.*))"
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-push
  plan:
  - get: concourse-examples
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          repository: concourse/oci-build-task
      inputs:
      - name: concourse-examples
      outputs:
      - name: image
      params:
        CONTEXT: concourse-examples/contexto
        UNPACK_ROOTFS: "true" # only needed if using image in a future step
      run:
        path: build
  - put: simple-image
    params:
      image: image/image.tar
